### ISSUE TITLE
Смотреть онлайн ТВ

### ISSUE THREAD

**Issue by pokras** [sciguy14/JBLUM.com-v3-Circuit-Board-Header#1]
[url= a href=http://prostosoftik.w.pw/] [u]Смотреть онлайн ТВ[/u][/url] 
бесплатно [u]можно посмотреть у нас [/u]на сайте есть[url= a href=http://prostosoftik.w.pw/] онлайн покер Тв [/url] 
этот канал идет круглосуточно при этом на нем нет ни какой рекламмы и покзывают восновном покерные 
[url= a href=http://prostosoftik.w.pw/]турниры для фанатов покера[/url] я постоянно его смотрю бесплатно еще мне нравится [url= a href=http://prostosoftik.w.pw/] онлайн тв Дискавери Смотреть[/url] 
 
[u][b]Заходите смотрите думою вампонравится[/b][/u] !!!!!!!! 
 
[url= a href=http://www.pokras7777.vx6.ru] базы трастовых сайтов 2015[/url]

**Comment by sciguy14** [comment]
1. I can't read Cyrillic (I think that's what this is)
2. I'm pretty sure it's spam anyways, judging by the links and bbCode markers.
3. Closed.
